# Generated by Django 4.2.5 on 2023-09-29 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directmessages', '0003_alter_directmessagemodel_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessagemodel',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directmessagemodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
